### ISSUE TITLE
Stop using Log.write

### ISSUE THREAD

**Issue by IceDragon200** [archSeer/Scarlet#40]
Sad discovery after using multiple servers for the first time, Logs are shared across servers.
THIS IS A NO.

So, we'll need a logs attribute on servers which contain a `LogPool` (maybe I should consider renaming that to LogBuffer)

In addition I believe times should be stored in ISO format instead of integers, so timezones remain intact

**Comment by archSeer** [comment]
Just make the Logger per-server instead of a singleton, problem solved. No need for Pools and Buffers and whatnot.

**Comment by IceDragon200** [comment]
@archSeer  `Log` is the model, which represents 1 event, the `LogPool` is a glorified `RingBuffer` of `Logs`, which is why I said we add the logs to the server, and don't confuse the `Scarlet.logger` with it, that is the Logger logger logger... `require 'logger'`, that one, if that makes any sense
